services:
  test-dev-vue:
    build:
      context: ../test-dev-vue
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: test-dev-vue
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - vue_build:/app/dist
    tty: true

  test-dev-nginx:
    image: nginx:alpine
    container_name: test-dev-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - vue_build:/usr/share/nginx/html:ro
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - test-dev-vue

volumes:
  vue_build:

networks:
  default:
    name: test-dev-net
